version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Updating pip and installing dependencies..."
      - pip install --upgrade pip
      - pip install databricks-cli databricks-sdk
      - pip install jq  # Install JSON validation tool for debugging

  pre_build:
    commands:
      - echo "Setting up Databricks authentication..."
      - export DATABRICKS_TOKEN="dapiee6e44bd23367fa14cb92cc95cf048cb"
      - export DATABRICKS_HOST="https://dbc-5f99fc48-0975.cloud.databricks.com"
      - echo -e "[default]\nhost = $DATABRICKS_HOST\ntoken = $DATABRICKS_TOKEN" > ~/.databrickscfg
      - chmod 600 ~/.databrickscfg  # Secure the file

      - echo "Checking Databricks connection..."
      - nslookup dbc-5f99fc48-0975.cloud.databricks.com
      - curl -I $DATABRICKS_HOST

      - echo "Verifying Databricks workspace access..."
      - databricks workspace ls

  build:
    commands:
      - echo "Deploying Databricks Job with Bundles..."
      - databricks deploy --bundle-file databricks.yml --target development || { echo "Deployment failed! Exiting..."; exit 1; }

      - echo "Triggering Job Execution..."
      - databricks jobs run-now --job-id <YOUR_JOB_ID> || { echo "Failed to trigger Databricks job! Exiting..."; exit 1; }

  post_build:
    commands:
      - echo "Deployment Completed Successfully!"

artifacts:
  files:
    - "**/*"
