version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install databricks-cli==0.205
  pre_build:
    commands:
      - export DATABRICKS_TOKEN=$(aws ssm get-parameter --name "/databricks/token" --with-decryption --query "Parameter.Value" --output text)
      - export DATABRICKS_HOST=https://<your-workspace>.cloud.databricks.com
      - echo -e "[default]\nhost = $DATABRICKS_HOST\ntoken = $DATABRICKS_TOKEN" > ~/.databrickscfg
  build:
    commands:
      - echo "Deploying basic notebook bundle..."
      - databricks bundle deploy